/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container': '#f0edf0',
        'on-primary-fixed-variant': '#4500d8',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-container': '#c70039',
        background: '#fcf8fb',
        'inverse-on-surface': '#f3f0f2',
        'on-surface-variant': '#484456',
        'outline-variant': '#c9c3da',
        'surface-dim': '#dcd9dc',
        'on-error-container': '#93000a',
        'surface-bright': '#fcf8fb',
        'on-surface': '#1c1b1d',
        'surface-container-low': '#f6f3f5',
        'surface-container-high': '#eae7ea',
        'surface-container-highest': '#e5e1e4',
        'tertiary-fixed-dim': '#ffb3b5',
        'on-secondary-fixed': '#002021',
        'on-secondary-fixed-variant': '#004f53',
        'surface-variant': '#e5e1e4',
        'on-tertiary-fixed': '#40000c',
        tertiary: '#9a002a',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#63f7ff',
        'inverse-primary': '#c9bfff',
        'on-primary': '#ffffff',
        'on-secondary-container': '#006c71',
        'secondary-container': '#00f4fe',
        'on-background': '#1c1b1d',
        primary: '#4900e5',
        'on-primary-fixed': '#1b0063',
        'tertiary-fixed': '#ffdada',
        'primary-container': '#6236ff',
        'primary-fixed-dim': '#c9bfff',
        outline: '#797488',
        'on-tertiary-fixed-variant': '#920027',
        surface: '#fcf8fb',
        secondary: '#00696e',
        'on-primary-container': '#e3dbff',
        'surface-tint': '#5d2ffa',
        'on-tertiary-container': '#ffd6d7',
        'secondary-fixed-dim': '#00dce5',
        'inverse-surface': '#313032',
        'surface-container-lowest': '#ffffff',
        error: '#ba1a1a',
        'primary-fixed': '#e5deff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'margin-mobile': '20px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'stack-sm': '8px',
        'margin-tablet': '32px',
        gutter: '16px',
      },
      fontFamily: {
        'body-lg': ['Geist', 'sans-serif'],
        'label-sm': ['Geist', 'sans-serif'],
        'display-lg': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'headline-sm': ['Sora', 'sans-serif'],
        'display-lg-mobile': ['Sora', 'sans-serif'],
        'label-md': ['Geist', 'sans-serif'],
        headline: ['Sora', 'sans-serif'],
        display: ['Sora', 'sans-serif'],
        body: ['Geist', 'sans-serif'],
        label: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg': [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg-mobile': [
          '32px',
          { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-md': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
